# Generated by Django 5.2.7 on 2025-11-02 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_student_admission_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_student_e7126a_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_departm_a8d1ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_status_5e2210_idx',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expected_graduation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='extra_curricular',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_occupation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel_resident',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_institution',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_qualification',
        ),
        migrations.RemoveField(
            model_name='student',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scholarship_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='transport_user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Admission'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Head of Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Guardian's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Guardian's Phone"),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], verbose_name='Year'),
        ),
    ]
