# Generated by Django 5.2.7 on 2025-11-01 10:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0002_alter_student_options_student_admission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['department', 'designation', 'user__first_name'], 'verbose_name_plural': 'Faculty'},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='experience',
        ),
        migrations.AddField(
            model_name='faculty',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='faculty/certificates/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('visiting', 'Visiting'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='industry_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='faculty/resumes/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teaching_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_experience',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total years of experience', max_digits=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['employee_id'], name='faculty_fac_employe_5f553f_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['department', 'designation'], name='faculty_fac_departm_c5ee9f_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['status'], name='faculty_fac_status_ddd7aa_idx'),
        ),
    ]
