# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_options_remove_faculty_experience_and_more'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['faculty_id'], 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculty'},
        ),
        migrations.RemoveIndex(
            model_name='faculty',
            name='faculty_fac_employe_5f553f_idx',
        ),
        migrations.RemoveIndex(
            model_name='faculty',
            name='faculty_fac_departm_c5ee9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='faculty',
            name='faculty_fac_status_ddd7aa_idx',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='address',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='city',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='industry_experience',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_promotion_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='research_interests',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='state',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='teaching_experience',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='total_experience',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='Faculty ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Office Location'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='students.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
