# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='lab_fee',
            new_name='exam_fee',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='payment_method',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('department', 'year')},
        ),
        migrations.AddField(
            model_name='feepayment',
            name='academic_year',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., 2024-2025', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='semester',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10, verbose_name='Total Amount Due'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Payment'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived Off')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='department',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='students.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='library_fee',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='misc_fee',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='total_fee',
        ),
    ]
