# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courseassignment_course_and_more'),
        ('exams', '0001_initial'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Exam Name')),
                ('exam_type', models.CharField(choices=[('midterm_1', 'Mid-Term 1'), ('midterm_2', 'Mid-Term 2'), ('final', 'Final Exam'), ('sessional', 'Sessional'), ('practical', 'Practical')], max_length=20, verbose_name='Exam Type')),
                ('exam_date', models.DateField(verbose_name='Date of Exam')),
                ('max_marks', models.PositiveIntegerField(verbose_name='Maximum Marks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_date', 'course'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.PositiveIntegerField(verbose_name='Marks Obtained')),
                ('grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='Grade')),
                ('is_pass', models.BooleanField(default=True, verbose_name='Pass/Fail Status')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['exam', 'student'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.DeleteModel(
            name='Examination',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
