# Generated by Django 5.2.7 on 2025-11-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0002_alter_student_options_student_admission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'semester', 'course_code']},
        ),
        migrations.AddField(
            model_name='course',
            name='assignment_weightage',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='continuous_assessment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('lab', 'Laboratory'), ('project', 'Project'), ('seminar', 'Seminar')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='final_weightage',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='course',
            name='has_final_exam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='course',
            name='midterm_weightage',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='min_cgpa_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='online_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='reference_books',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='courses/syllabus/'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorial_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='courses_cou_course__897db7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'semester'], name='courses_cou_departm_272ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
    ]
