# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_course_assignment_weightage_and_more'),
        ('faculty', '0002_alter_faculty_options_remove_faculty_experience_and_more'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='faculty',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_course__897db7_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_departm_272ecc_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_is_acti_3c7e41_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assignment_weightage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='continuous_assessment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='final_weightage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='has_final_exam',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecture_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='midterm_weightage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_cgpa_required',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='online_resources',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practical_assessment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practical_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reference_books',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutorial_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='faculty.faculty', verbose_name='Lead Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Course Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('project', 'Project'), ('seminar', 'Seminar')], default='theory', max_length=10, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='CourseAssignment',
        ),
    ]
