# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_transport', '0001_initial'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelroom',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='occupied_rooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='total_rooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='warden',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='allocation_date',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='source',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='hostel',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='date_allocated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportroute',
            name='bus_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Bus Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Hostel Name'),
        ),
        migrations.AlterField(
            model_name='hostelallocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocation', to='students.student'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='driver_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='route_name',
            field=models.CharField(max_length=255, verbose_name='Route Name'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='Room Number')),
                ('capacity', models.PositiveIntegerField(default=3)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel_transport.hostel')),
            ],
            options={
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.AlterField(
            model_name='hostelallocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hostel_transport.room'),
        ),
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_allocated', models.DateField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hostel_transport.transportroute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_allocation', to='students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='TransportAssignment',
        ),
        migrations.DeleteModel(
            name='HostelRoom',
        ),
    ]
