# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courseassignment_course_and_more'),
        ('faculty', '0003_alter_faculty_options_and_more'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10, verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('room_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room Number / Location')),
                ('year', models.IntegerField(default=1, verbose_name='Year')),
                ('semester', models.IntegerField(default=1, verbose_name='Semester')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='students.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['department', 'year', 'semester', 'day_of_week', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
