# Generated by Django 5.2.7 on 2025-11-02 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_attendance_approved_by_and_more'),
        ('courses', '0002_alter_course_options_course_assignment_weightage_and_more'),
        ('faculty', '0002_alter_faculty_options_remove_faculty_experience_and_more'),
        ('students', '0003_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__date_61f2e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__student_e4c8ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__status_132c06_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='faculty',
            field=models.ForeignKey(help_text='Faculty member who took the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
    ]
